### ISSUE TITLE
does not connect to RabbitMQ MQTT plugin

### ISSUE THREAD

**Issue by huwylphi** [Lugaresi/codesys2-mqtt-library#1]
Thanks for this great lib. It's the only one I've found working with CodeSys 2.3.
I've tested the lib with [Mosiquitto MQTT Brocker](https://mosquitto.org/) and it seems to be working. But unfortunately with the [RabbitMQ MQTT plugin](https://www.rabbitmq.com/mqtt.html) I always have 

> 'Waiting for "Connack" from MQTT-Broker Timed out'

 error message just after connection.

**Comment by ddokupil** [comment]
The same issue on my side, except I'm trying to use mosquitto (v2.0.11). What's interesting I managed to connect once and used it for a couple of months but lost the code due to data loss and can't manage to configure it anymore.

**Comment by huwylphi** [comment]
I could test it again with RabbitMQ 3.11.5 and its MQTT plugin and now the current _mqtt.lib_ master version from December 19 2022 works!

It was a bit tricky to get RabbitMQ's MQTT allowing connection from remote clients, but after reading the doc I could make it work.

For one that would like to use RabbitMQ as broker here is my docker-compose content:
```
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - /mnt/gfsv1/docker/rabbitmq/etc/:/etc/rabbitmq/
    ports:
      - 5672:5672   # AMQP protocol port
      - 15672:15672 # HTTP management UI
      - 61613:61613 # MQTT plugin protocol port

# enable management and MQTT plugins
#    command: >
#      bash -c "rabbitmq-plugins enable rabbitmq_management
#      && rabbitmq-plugins enable rabbitmq_mqtt"
```

Then in the _/etc/rabbitmq/_ path (mapped) I use the following RabbitMQ configuration file _rabbitmq.conf_:
```
# AMQP protocol port
listeners.tcp.default = 5672
# Allow remote connection as guest user
loopback_users.guest = false
# HTTP management UI
management.tcp.port = 15672
management.tcp.ip = 0.0.0.0
# MQTT plugin protocol port
mqtt.listeners.tcp.1 = 0.0.0.0:61613
mqtt.default_user = guest
mqtt.default_pass = guest
mqtt.allow_anonymous = false
# further optional settings (see official documentation)
mqtt.tcp_listen_options.keepalive = true
mqtt.num_acceptors.tcp = 10
mqtt.exchange = amq.topic
mqtt.subscription_ttl = 1800000
```
The RabbitMQ server source repository contains an example rabbitmq.conf file named [rabbitmq.conf.example](https://github.com/rabbitmq/rabbitmq-server/blob/v3.8.x/deps/rabbit/docs/rabbitmq.conf.example). It contains examples of most of the configuration items you might want to set (with some very obscure ones omitted), along with documentation for those settings.

I guess after the big refactoring, last new features and fixes regarding the CONNECT MQTT frame done the last 2 years we made it possible to use this lib to connect with RabbitMQ like a Mosquitto MQTT broker.

I think we can close that issue now.
