### ISSUE TITLE
Subscription and mutliple messages in one TCP frame

### ISSUE THREAD

**Issue by cholokla** [Lugaresi/codesys2-mqtt-library#3]
Hello,
I'm using your library with Wago 750-889 and works great with publishing and simple subscription.

However, I have a problem when I subscribe to the wildcard topic ('wago/outputs/+/set') and many messages are transmitted from Homeassistant almost in the same time (using Mosquitto server).
I've analysed tcpdump log and saw that when several messages are stuffed in one frame (Nagle's Algorithm) only the first one is being received by the FB_MQTTClient.
I've used "set_tcp_nodelay" in the Mosquitto configuration but that helps only partially - there are still some messages in one frame.

Is there any possibility to support such case?

![mqtt_tcp_problem](https://user-images.githubusercontent.com/15654069/198870150-8cdfb310-7a82-401a-804d-33cfe3530ab6.png)

Regards,
robert

**Comment by cholokla** [comment]
Hi Philippe,
thank you for your answer :)

Well, maybe the quickest way to reproduce that case is to setup Homeassistant in docker, configure several mqtt switches at one card and try to turn them on at once ;)
![ha_wago](https://user-images.githubusercontent.com/15654069/199355855-44965f3c-6bc7-44b8-8f3f-7153be2bbd34.png)

There are some free apps that can create raw TCP packets though (e.g. https://packetsender.com/) but as I understand you should first create CONNECT and then PUBLISH frame.

I can try to write simple app, that publishes several messages in a row, but can't be sure if the "mutliple frame" will be created.

Greetings,
Robert

**Comment by huwylphi** [comment]
Hi Robert,
I can try to setup Homeassistant in docker and configure it like you proposed.
I always wanted to try Homeassistant, so now this could be my opportunity...
I'm currently a bit busy but hope I'll find some time to work on that interesting use case.
Kind regards,
Philippe

**Comment by cholokla** [comment]
Great, these are my first steps using Home Assistant, because I was using Openhab before, but I can try to help.

I've installed complete Hass OS (recommended and quickest way) on my Synology NAS but you can also install it on the VirtualBox: [https://www.home-assistant.io/installation/.](https://www.home-assistant.io/installation/)
Nextly you should install MQTT Broker integration (I'm using Mosquitto here).

Then, you can configure mqtt switches in the HA's configuration.yaml (simplest way is using the Visual Studio Code integration), for example:
```
mqtt:
  switch:
    - name: "Wago Mqtt Output 1"
      state_topic: "wago/outputs/1/get"
      command_topic: "wago/outputs/1/set"
      state_on: "ON"
      state_off: "OFF"
      retain: false
    - name: "Wago Mqtt Output 2"
      state_topic: "wago/outputs/2/get"
      command_topic: "wago/outputs/2/set"
      state_on: "ON"
      state_off: "OFF"
      retain: false
    - name: "Wago Mqtt Output 3"
      state_topic: "wago/outputs/3/get"
      command_topic: "wago/outputs/3/set"
      state_on: "ON"
      state_off: "OFF"
      retain: false
    - name: "Wago Mqtt Output 4"
      state_topic: "wago/outputs/4/get"
      command_topic: "wago/outputs/4/set"
      state_on: "ON"
      state_off: "OFF"
      retain: false
```
(I'm publishing "get" message from the PLC as soon as the state of the output is changed, but you can also use the optimistic flag in the HA)

and declare subscription in codesys:
```
mqtt(
	i_sBrokerAddress := '192.168.0.37',
        i_uiPort := 1883,
	i_sUsername := 'xxx',
	i_sPassword := 'xxx',
	i_sSubscribeTopic := 'wago/outputs/+/set',
	i_xPublish := FALSE,
	i_xSubscribe := TRUE,
	i_sClientIdentifier := 'WAGO_SUB',
	i_xCleanSession := FALSE,
	i_tCommTimeout :=  t#10s
);
```

Last step is to create card on the HA dashboard with all the switch entities and a button in header that can turn on/off all of them.

Regards,
robert
